name: ConnectBot Build_b

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          target: default
          arch: x86_64
          profile: Nexus 4
          script: ./gradlew connectedCheck --continue

      - name: Build
        run: ./gradlew build bundleGoogleRelease

      - name: Prepare release
        if: ${{ github.event_name == 'push' }}
        run: |
          if git describe --exact-match; then \
            TAGGED=yes
          fi

          if [[ -n $TAGGED ]]; then
            GITHUB_TAG="$(git describe)"
            echo "${GITHUB_TAG}" > tag.txt
            echo "Release ${GITHUB_TAG}" > release-title.txt
          else \
            GITHUB_TAG="git-$(git describe)"
            GITHUB_TITLE="$(git log -1 --pretty=%B | head -1)"
            echo "${GITHUB_TAG}" > tag.txt
            echo "${GITHUB_TAG}: ${GITHUB_TITLE}" > release-title.txt
          fi
          cp ./app/build/outputs/apk/oss/release/app-oss-release-unsigned.apk ConnectBot-${GITHUB_TAG}-oss-unsigned.apk
          cp ./app/build/outputs/apk/google/release/app-google-release-unsigned.apk ConnectBot-${GITHUB_TAG}-google-unsigned.apk
          cp ./app/build/outputs/bundle/googleRelease/app-google-release.aab ConnectBot-${GITHUB_TAG}-google-unsigned.aab
          cp ./app/build/outputs/native-debug-symbols/googleRelease/native-debug-symbols.zip ConnectBot-${GITHUB_TAG}-google.native-debug-symbols.zip
          cp ./app/build/outputs/native-debug-symbols/ossRelease/native-debug-symbols.zip ConnectBot-${GITHUB_TAG}-oss.native-debug-symbols.zip
  
      - name: Store artifacts for upload
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@master
        with:
          name: apk
          path: |
            release-title.txt
            tag.txt
            ConnectBot-*-unsigned.apk
            ConnectBot-*-unsigned.aab
            ConnectBot-*.native-debug-symbols.zip
